version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql


#    networks:
#      - mynetwork

  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
#    networks:
#      - mynetwork
    depends_on:
      - db

#networks:
#  mynetwork:
#    driver: bridge

volumes:
  db_data:
    driver: local